/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vmloft_develop_library_tools_recorder_VMLame */

#ifndef _Included_com_vmloft_develop_library_tools_recorder_VMLame
#define _Included_com_vmloft_develop_library_tools_recorder_VMLame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vmloft_develop_library_tools_recorder_VMLame
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_vmloft_develop_library_tools_recorder_VMLame_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_vmloft_develop_library_tools_recorder_VMLame
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_com_vmloft_develop_library_tools_recorder_VMLame_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     com_vmloft_develop_library_tools_recorder_VMLame
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_vmloft_develop_library_tools_recorder_VMLame_flush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_vmloft_develop_library_tools_recorder_VMLame
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vmloft_develop_library_tools_recorder_VMLame_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
