/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vmloft_develop_library_tools_utils_VMCrypto */

#ifndef _Included_com_vmloft_develop_library_tools_utils_VMCrypto
#define _Included_com_vmloft_develop_library_tools_utils_VMCrypto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vmloft_develop_library_tools_utils_VMCrypto
 * Method:    crypStr2SHA1
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vmloft_develop_library_tools_utils_VMCrypto_crypStr2SHA1
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_vmloft_develop_library_tools_utils_VMCrypto
 * Method:    crypStr2MD5
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vmloft_develop_library_tools_utils_VMCrypto_crypStr2MD5
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
